Added archive message and disabled Github actions
LeastAuthority/Transfer pull request #127
Opened 2022-10-06 08:10 UTC by donpui

Added not and disabled github actions. Later on we can change repository setting to become archived

---

## Code Review Checklist (to be filled out by reviewer)

- [ ] Description accurately reflects what changes are being made.
- [ ] Description explains why the changes are being made (or references an issue containing one).
- [ ] The PR appropriately sized.
- [ ] New code has enough tests.
- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [ ] Existing documentation is up-to-date, if impacted.

2022-10-07 07:20 UTC, donpui commented on .github/workflows/main.yml
> +#         run: twist wormhole-mailbox --usage-db=usage.sqlite &
So this is old repo, which we will archive, should we make here any changes?

2022-10-07 14:06 UTC, meejah commented on .github/workflows/main.yml
> +#         run: twist wormhole-mailbox --usage-db=usage.sqlite &
oh, i see it's all just commented-out. just delete instead of commenting, I'd say...

2022-10-11 14:02 UTC, on-ba requested changes

2022-10-11 14:02 UTC, on-ba commented on README.md
> +## **Note:** This repository is not maintened anymore. Frontend application code was refactored and new version is available at [Winden repository](https://github.com/LeastAuthority/winden). Be aware
Suggestion: 

> This repository is not maintained anymore. Be aware that the packages are outdated and may have security issues. The front-end application code was refactored and a new version is available as the [Winden](https://github.com/LeastAuthority/winden) repository.

2022-10-11 16:11 UTC, donpui commented on README.md
> +## **Note:** This repository is not maintened anymore. Frontend application code was refactored and new version is available at [Winden repository](https://github.com/LeastAuthority/winden). Be aware
Ok

2022-10-11 16:25 UTC, on-ba approved these changes

2022-10-11 16:44 UTC, merged