changes to support the reader interface to wormhole-william
LeastAuthority/Transfer pull request #30
Opened 2021-07-19 17:10 UTC by vu3rdd

This change gets rid of the large buffer at the sending side and makes use of the streaming interface supported by wormhole-william.

2021-07-19 17:11 UTC, vu3rdd commented
These changes depend on the corresponding changes in wormhole-william (changes for which are raised as a separate PR to that repo).

2021-11-02 11:41 UTC, bryanchriswhite commented
Task linked: [CU-1p7nf3k Implement send-side streaming](https://app.clickup.com/t/1p7nf3k)

2021-11-15 09:19 UTC, bryanchriswhite commented on src/worker.ts
> +const bufferSize = 16384 // to match the sending side buffersize
`bufferSize` is only used in `handleReceiveFileData` on line 110. I'm not sure I understand this change.

The size of the send-side buffer is determined by the size of the `ArrayBuffer` that's passed to [`FileWrapper#Read`](https://github.com/LeastAuthority/wormhole-william/blob/master/wasm/client.go#L127).

If we want to change the size of the receive-side buffer we currently also need to change [client.go:345](https://github.com/LeastAuthority/wormhole-william/blob/master/wasm/client.go#L345).

2021-11-15 09:21 UTC, bryanchriswhite requested changes
@vu3rdd thanks for doing this! My apologies for the delay in reviewing :pray: 

I have a copule of questions:

1. Am I misunderstanding that buffer size change?
2. Can we update the `wormhole-william` submodule to `master` in this PR now that [wormhole-william#19](https://github.com/LeastAuthority/wormhole-william/pull/19) is merged?

2021-11-15 11:56 UTC, bryanchriswhite approved these changes

2021-11-15 11:56 UTC, merged