update / fix readme
LeastAuthority/Transfer pull request #47
Opened 2021-09-28 07:53 UTC by bryanchriswhite

- Fixes a formatting error: extra "```"
- Renames MyFileTransfer to Transfer (matching the UI)
- Adds some detail to project description and build instructions

---

## Code Review Checklist (to be filled out by reviewer)

- [ ] Description accurately reflects what changes are being made.
- [ ] Description explains why the changes are being made (or references an issue containing one).
- [ ] The PR appropriately sized.
- [ ] New code has enough tests.
- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [ ] Existing documentation is up-to-date, if impacted.

2021-09-28 09:58 UTC, on-ba commented on README.md
```suggestion

## Status

This web app is in 'alpha' state, and **not ready for production use**.
```

2021-09-28 09:59 UTC, on-ba requested changes
Added a single comment to communicate 'Status' information.

2021-09-28 11:24 UTC, on-ba commented on README.md
> +This web app is in 'alpha' state, and **not ready for production use**.
```suggestion
This web app is in 'alpha' state, and **not ready for production use**.

```

2021-09-30 07:22 UTC, vu3rdd approved these changes

2021-09-30 07:22 UTC, merged